/* The command line, which is a shipped binary and had no tests at all.

   Run as a Playwright test purely to borrow the fixture server; the CLI drives
   its own browser and nothing here touches the `page` fixture. */

import { test, expect } from "@playwright/test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readFileSync, rmSync, mkdtempSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";

const run = promisify(execFile);
const CLI = "dist/cli.js";
/* Follows the config rather than repeating its number. */
const PORT = Number(process.env.FIXTURE_PORT ?? 4173);
const PAGE = `http://127.0.0.1:${PORT}/prose.html`;

interface Run {
  code: number;
  stdout: string;
  stderr: string;
}

async function quoin(args: string[]): Promise<Run> {
  try {
    const { stdout, stderr } = await run(process.execPath, [CLI, ...args], {
      timeout: 120_000,
      maxBuffer: 16 * 1024 * 1024,
    });
    return { code: 0, stdout, stderr };
  } catch (error) {
    const e = error as { code?: number; stdout?: string; stderr?: string };
    return { code: e.code ?? 1, stdout: e.stdout ?? "", stderr: e.stderr ?? "" };
  }
}

/* These drive their own browsers, so running the file under all three Playwright
   projects would run the same work three times and report it as three results.
   Pinned to one project; the engines are covered inside the test. */
test.skip(({ browserName }) => browserName !== "chromium", "drives its own browsers");

test.describe.configure({ mode: "serial" });

test("--help exits zero and lists the three commands", async () => {
  const result = await quoin(["--help"]);
  expect(result.code).toBe(0);
  for (const command of ["check", "seat", "engine"]) {
    expect(result.stdout).toContain(command);
  }
});

test("no arguments prints usage rather than doing something", async () => {
  const result = await quoin([]);
  expect(result.code).toBe(0);
  expect(result.stdout).toContain("baseline grid");
});

test("an unknown command and a missing URL both fail loudly", async () => {
  const unknown = await quoin(["bogus"]);
  expect(unknown.code).toBe(2);
  expect(unknown.stderr).toContain("unknown command");

  const noUrl = await quoin(["check"]);
  expect(noUrl.code).toBe(2);
  expect(noUrl.stderr).toContain("needs a URL");

  const badFlag = await quoin(["check", PAGE, "--pitch", "banana"]);
  expect(badFlag.code).toBe(2);
  expect(badFlag.stderr).toContain("wants a number");

  const badViewport = await quoin(["check", PAGE, "--viewport", "wide"]);
  expect(badViewport.code).toBe(2);
  expect(badViewport.stderr).toContain("WIDTHxHEIGHT");
});

test("a pitch of zero is refused by the CLI as well as by the library", async () => {
  /* The validation lives in `gridConfig`, and the point of this is that the
     error reaches the shell rather than surfacing as an unhandled rejection or,
     worse, a report of a perfect page. */
  const result = await quoin(["check", PAGE, "--pitch", "0"]);
  expect(result.code, "it did not report success").not.toBe(0);
  expect(
    `${result.stderr}${result.stdout}`.toLowerCase(),
    "and it said why"
  ).toContain("pitch");
});

test("check reports a page and its JSON parses", async () => {
  const human = await quoin(["check", PAGE]);
  expect(human.code).toBe(0);
  expect(human.stdout).toContain("on a 8px grid");
  expect(human.stdout).toContain("distinct drift");

  const json = await quoin(["check", PAGE, "--json"]);
  expect(json.code).toBe(0);

  const parsed = JSON.parse(json.stdout) as {
    url: string;
    percent: number;
    report: { total: number; onGrid: number; distinctDrifts: number };
    worst: { drift: number; path: string; sample: string }[];
  };

  expect(parsed.url).toBe(PAGE);
  expect(parsed.report.total, "it found the fixture's paragraphs").toBeGreaterThan(5);
  expect(parsed.percent).toBeGreaterThanOrEqual(0);
  expect(parsed.percent).toBeLessThanOrEqual(100);
  expect(Array.isArray(parsed.worst)).toBe(true);
});

test("--min is a gate: non-zero below the floor, zero above it", async () => {
  /* The whole reason the CLI exists in CI. */
  const failing = await quoin(["check", PAGE, "--min", "95"]);
  expect(failing.code, "below the floor").toBe(1);
  expect(failing.stderr).toContain("below the");

  const passing = await quoin(["check", PAGE, "--min", "1"]);
  expect(passing.code, "above the floor").toBe(0);
});

test("seat writes a stylesheet that is real CSS", async () => {
  const dir = mkdtempSync(join(tmpdir(), "quoin-cli-"));
  const out = join(dir, "baseline.css");

  try {
    const result = await quoin(["seat", PAGE, "-o", out, "--ignore", ".display"]);
    expect(result.code).toBe(0);
    expect(result.stdout).toContain("CSS written to");

    const css = readFileSync(out, "utf8");
    expect(css).toContain("Generated by quoin");
    expect(css).toContain("Grid: 8px");
    expect(css, "no runtime attribute in the shipped output").not.toContain(
      "data-quoin-seat"
    );
    expect(css).not.toContain("NaN");
    expect(css).not.toContain("undefined");
    expect(css.match(/\{/g)?.length ?? 0, "it wrote some rules").toBeGreaterThan(3);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("seat --json reports before and after", async () => {
  const result = await quoin(["seat", PAGE, "--json", "--ignore", ".display"]);
  expect(result.code).toBe(0);

  const parsed = JSON.parse(result.stdout) as {
    before: { onGrid: number; total: number };
    after: { onGrid: number; total: number };
    passes: number;
    css: string;
  };

  expect(parsed.after.onGrid, "seating improved the page").toBeGreaterThan(
    parsed.before.onGrid
  );
  expect(parsed.passes).toBeGreaterThanOrEqual(1);
  expect(parsed.css.length).toBeGreaterThan(50);
});

test("engine reports what this browser's metrics do", async () => {
  const result = await quoin(["engine", PAGE, "--json"]);
  expect(result.code).toBe(0);

  const parsed = JSON.parse(result.stdout) as {
    browser: string;
    rasterised: boolean;
    fontTable: boolean;
  };

  expect(parsed.browser).toBe("chromium");
  expect(typeof parsed.rasterised).toBe("boolean");
  expect(typeof parsed.fontTable).toBe("boolean");
  /* Chromium has shipped text-box-trim since 133. If this ever reads false the
     probe has broken, not the browser. */
  expect(parsed.fontTable, "chromium can read the font table").toBe(true);
});

test("a URL that does not resolve fails with a message rather than a stack", async () => {
  const result = await quoin(["check", "http://127.0.0.1:9/nothing-here"]);
  expect(result.code).toBe(2);
  expect(result.stderr).toContain("could not load");
  expect(result.stderr, "no raw stack trace").not.toContain("at async");
});

/* ------------------------------------------------------------------ *
   Fitting, which is the only command that need not open a browser
 * ------------------------------------------------------------------ */

test("@fit a design naming its font files is fitted without a browser", async () => {
  /*
     The adoption question. A PostCSS step, a Vite plugin, a token pipeline or an
     agent with no display can all read an OS/2 table; none of them can be asked
     to install Playwright first. When every family names a file, nothing here
     launches anything.

     Run as a Playwright test only because it needs `dist/` to exist, which the
     unit suite runs before. Nothing in it touches a browser.
  */
  const dir = mkdtempSync(join(tmpdir(), "quoin-fit-"));
  try {
    const fonts = resolve("test/browser/fixtures/fonts");
    if (!existsSync(join(fonts, "Lato.ttf"))) {
      test.skip(true, "no font corpus: run `npm run fonts`");
      return;
    }

    const design = {
      pitch: 8,
      families: [
        {
          role: "body",
          font: "Lato",
          file: join(fonts, "Lato.ttf"),
          steps: [
            { name: "body", size: 17, ratio: 1.5, space: 24 },
            { name: "h1", size: 44, leading: 48, space: 56 },
          ],
        },
      ],
    };

    const path = join(dir, "design.json");
    writeFileSync(path, JSON.stringify(design));

    const started = Date.now();
    const result = await quoin(["fit", "--design", path, "--json"]);
    const took = Date.now() - started;

    expect(result.code, result.stderr).toBe(0);

    const parsed = JSON.parse(result.stdout) as {
      cost: number;
      origin: number;
      families: {
        steps: { name: string; size: number; leading: number; space: number; cap: number }[];
      }[];
      fonts: { font: string; problem: string | null }[];
      css: string;
    };

    /* Lato declares 1433 on a 2000 em, so 17px has a cap of 12.1805 and 44px
       has 31.526. Both engines drew exactly those. */
    const [body, h1] = parsed.families[0]!.steps;
    expect(body!.size, "the size is untouched").toBe(17);
    expect(h1!.size).toBe(44);
    expect(Math.abs(body!.cap - 12.181)).toBeLessThan(0.01);

    /* The property the whole method rests on. */
    for (const step of parsed.families[0]!.steps) {
      const closes = (step.space + step.cap) % 8;
      expect(
        Math.min(closes, 8 - closes),
        `${step.name}: space ${step.space} plus cap ${step.cap} is not a whole row`
      ).toBeLessThan(0.01);
    }

    expect(parsed.fonts[0]!.problem, "the file was readable").toBeNull();
    expect(parsed.css).toContain("text-box-trim: trim-both");

    /* Not a benchmark, a proof that no browser started. Launching Chromium and
       loading a page has never taken under a second on any machine this has run
       on; reading two tables out of a file takes a hundredth of that. */
    expect(took, `took ${took}ms, which is long enough to have started a browser`).toBeLessThan(
      1500
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("@fit a font with no declared cap height is named, not silently dropped", async () => {
  const dir = mkdtempSync(join(tmpdir(), "quoin-fit-"));
  try {
    const fonts = resolve("test/browser/fixtures/fonts");
    if (!existsSync(join(fonts, "AwkwardAbsent.ttf"))) {
      test.skip(true, "no font corpus: run `npm run fonts`");
      return;
    }

    const path = join(dir, "design.json");
    writeFileSync(
      path,
      JSON.stringify({
        pitch: 8,
        families: [
          {
            role: "body",
            font: "Absent",
            file: join(fonts, "AwkwardAbsent.ttf"),
            steps: [{ name: "body", size: 17, ratio: 1.5 }],
          },
        ],
      })
    );

    const result = await quoin(["fit", "--design", path, "--json"]);
    const parsed = JSON.parse(result.stdout) as {
      unavailable: boolean;
      fonts: { problem: string | null }[];
    };

    expect(parsed.unavailable, "nothing could be fitted").toBe(true);
    expect(parsed.fonts[0]!.problem, "and it says why").toMatch(/OS\/2|cap height/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("@fit a font declaring an impossible cap height is refused", async () => {
  /*
     AwkwardHuge declares 1.4 em, which cannot be a cap height. Both Chromium and
     WebKit ignore it and measure the glyphs instead, drawing 0.7, so trusting
     the file would have produced a fit wrong by thirty pixels at a display size.
  */
  const dir = mkdtempSync(join(tmpdir(), "quoin-fit-"));
  try {
    const fonts = resolve("test/browser/fixtures/fonts");
    if (!existsSync(join(fonts, "AwkwardHuge.ttf"))) {
      test.skip(true, "no font corpus: run `npm run fonts`");
      return;
    }

    const path = join(dir, "design.json");
    writeFileSync(
      path,
      JSON.stringify({
        pitch: 8,
        families: [
          {
            role: "body",
            font: "Huge",
            file: join(fonts, "AwkwardHuge.ttf"),
            steps: [{ name: "body", size: 44, ratio: 1.1 }],
          },
        ],
      })
    );

    const result = await quoin(["fit", "--design", path, "--json"]);
    const parsed = JSON.parse(result.stdout) as {
      unavailable: boolean;
      fonts: { problem: string | null }[];
    };

    expect(parsed.unavailable).toBe(true);
    expect(parsed.fonts[0]!.problem).toMatch(/taller than the em/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
